services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localdb
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssw0rd
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    extra_hosts:
      - localhost:172.18.0.2
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
